const restaurants=[
{id:'guru',name:'Гуру',mark:'ГУРУ',type:'Грузинская кухня',note:'Тепло большого застолья',bg:'#e9eddf',color:'#435139',url:'https://rest.guru/',description:'Хинкали, хачапури и грузинское гостеприимство. Место для долгих разговоров и встреч за большим столом.'},
{id:'misto',name:'Misto',mark:'misto',type:'Итальянская кухня',note:'Маленькая Италия рядом',bg:'#f1e6db',color:'#77553e',url:'https://mistorest.ru/',description:'Итальянская классика и современные вкусы. Пицца, паста и маленькие поводы собраться вместе.'},
{id:'melodiya',name:'Мелодия',mark:'Мелодия',type:'Русская кухня',note:'Знакомые вкусы по-новому',bg:'#f0e1e6',color:'#884458',url:'https://melodiya.rest/',description:'Любимые вкусы русской кухни, тёплые воспоминания и атмосфера домашнего гостеприимства.'},
{id:'zonda',name:'Zonda',mark:'ZONDA',type:'Паназиатская кухня',note:'Вкус с ярким характером',bg:'#e2e8ea',color:'#334f5a',url:'https://zonda.rest/',description:'Яркие сочетания азиатской кухни: роллы, гёдза, димсамы и блюда, которые хочется пробовать вместе.'},
{id:'harats',name:"Harat’s",mark:"HARAT’S",type:'Ирландский паб',note:'Музыка. Друзья. Хороший вечер.',bg:'#e7e7dd',color:'#3b493a',url:'https://smolensk.harats.com/',description:'Ирландский паб для встреч с друзьями и вечеров с музыкой. Свой характер и непринуждённая атмосфера.'}
];
const assets={melodiya:'melodiya-logo.svg',guru:'guru-logo.png',misto:'misto-logo.svg',zonda:'zonda-logo.svg',interior:'misto-photo.jpg'};
const app=document.querySelector('#app');
function logo(r){return assets[r.id]?`<img src="assets/${assets[r.id]}" alt="${r.name}">`:`<span class="wordmark">${r.mark}</span>`}
function render(){const deliveryRoute=['#guru/delivery','#guru/cart'].includes(location.hash);document.body.classList.toggle('delivery-route',deliveryRoute);if(deliveryRoute){document.body.classList.add('guru-theme');app.replaceChildren(delivery);basketView=location.hash==='#guru/cart';drawDelivery();window.scrollTo(0,0);return;}const r=restaurants.find(r=>r.id===location.hash.slice(1));document.body.classList.toggle('guru-theme',r?.id==='guru');if(!r){app.innerHTML=`<section class="intro"><h1>Рестораны <em>Смоленска</em></h1><p>Забронируйте столик или закажите еду на дом.</p></section><nav class="restaurants" aria-label="Рестораны">${restaurants.map(r=>`<a class="card" href="#${r.id}" style="--bg:${r.bg};--color:${r.color}" aria-label="${r.name} — ${r.type}"><div class="logo-box">${logo(r)}</div><div class="card-info"><h2>${r.type}</h2><p>${r.note}</p></div><span class="arrow" aria-hidden="true">›</span></a>`).join('')}</nav>${assets.interior?`<div class="home-photo"><img src="assets/${assets.interior}" alt="Интерьер ресторана Misto"><span>У каждого места —<br>своя история.</span></div>`:''}`;}else{app.innerHTML=`<section class="detail" style="--bg:${r.bg};--color:${r.color}"><a href="#" class="back">← Все рестораны</a><div class="detail-brand">${logo(r)}</div><p class="eyebrow">${r.type} · Смоленск</p><h1>${r.name}</h1><p class="description">${r.description}</p><p class="detail-label">Как проведём этот день?</p><button class="action" data-action="delivery">Заказать доставку <span>↗</span></button><button class="action secondary" data-action="booking">Забронировать столик <span>↗</span></button><div id="notice" aria-live="polite"></div><a class="official" href="${r.url}" target="_blank" rel="noopener">Сайт ресторана ↗</a></section>`;app.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>{if(r.id==='guru' && b.dataset.action==='booking'){openGuruBooking();return;}if(r.id==='guru' && b.dataset.action==='delivery'){openGuruDelivery();return;}document.querySelector('#notice').innerHTML=`<p class="notice">${b.dataset.action==='delivery'?'Онлайн-доставка':'Онлайн-бронирование'} появится здесь позже. Сейчас можно перейти на сайт ресторана и посмотреть доступные способы связи.</p>`}));}window.scrollTo(0,0)}
window.addEventListener('hashchange',render);render();
