const categoryNames={all:'Все блюда','goryachaya-vypechka':'Выпечка',hinkali:'Хинкали','holodnye-zakuski':'Холодные закуски',salaty:'Салаты','goryachie-zakuski':'Горячие закуски',supy:'Супы','blyuda-na-mangale':'На мангале',goryachee:'Горячее',garniry:'Гарниры',deserty:'Десерты',sousy:'Соусы','varene-k-chayu':'Варенье'};
const basket=new Map();let category='all',basketView=false;
const delivery=document.createElement('section');delivery.className='delivery delivery-page';delivery.setAttribute('aria-label','Доставка из Гуру');
const rub=n=>n.toLocaleString('ru-RU')+' ₽';
const total=()=>guruMenu.reduce((s,p)=>s+p.price*(basket.get(p.id)||0),0);
const count=()=>[...basket.values()].reduce((s,n)=>s+n,0);
function controls(p){const n=basket.get(p.id)||0;return n?`<div class="quantity"><button data-change="${p.id}" data-delta="-1" aria-label="Убрать одну порцию ${p.name}">−</button><span aria-live="polite">${n}</span><button data-change="${p.id}" data-delta="1" aria-label="Добавить ещё ${p.name}">+</button></div>`:`<button class="add-dish" data-change="${p.id}" data-delta="1" aria-label="Добавить ${p.name}">${rub(p.price)} <span>+</span></button>`}
function drawDelivery(){delivery.innerHTML=`<a class="delivery-back" href="#guru">← Гуру</a><div class="delivery-head"><div><p class="eyebrow">ГУРУ · ДОСТАВКА</p><h2>${basketView?'Ваша корзина':'Меню ресторана'}</h2></div></div>${basketView?'<button class="menu-back">← Вернуться в меню</button>':`<div class="category-picker"><label for="menu-category">Категория</label><select id="menu-category">${Object.entries(categoryNames).map(([id,name])=>`<option value="${id}" ${category===id?'selected':''}>${name}</option>`).join('')}</select></div>`}<div class="delivery-body">${basketView?basketMarkup():`<h3>${categoryNames[category]}</h3><div class="dish-grid">${guruMenu.filter(p=>category==='all'||p.category===category).map(p=>`<article class="dish"><img src="${p.image}" alt="${p.name}" loading="lazy"><div class="dish-content"><h4>${p.name}</h4><span class="dish-weight">${p.weight}</span><p>${p.description}</p>${controls(p)}</div></article>`).join('')}</div><p class="menu-source">Меню и цены с сайта «Гуру». Итоговые условия доставки уточняются при подключении сервиса.</p>`}</div><div class="basket-bar">${basketView?`<div class="basket-total"><span>Сумма блюд</span><strong>${rub(total())}</strong></div><p class="demo-note">Это предварительная корзина. Оформление и оплата пока не подключены, заказ в ресторан не отправляется.</p>`:`<button class="show-basket"><span>Корзина <b>${count()}</b></span><strong>${rub(total())} →</strong></button>`}</div>`;
delivery.querySelector('.menu-back')?.addEventListener('click',()=>{location.hash='guru/delivery'});delivery.querySelector('.show-basket')?.addEventListener('click',()=>{location.hash='guru/cart'});delivery.querySelector('#menu-category')?.addEventListener('change',e=>{category=e.target.value;drawDelivery()});delivery.querySelectorAll('[data-change]').forEach(b=>b.onclick=()=>{const p=delivery.querySelector('.delivery-body'),y=p.scrollTop,x=delivery.querySelector('.categories')?.scrollLeft||0;const n=Math.max(0,(basket.get(b.dataset.change)||0)+Number(b.dataset.delta));n?basket.set(b.dataset.change,n):basket.delete(b.dataset.change);drawDelivery();delivery.querySelector('.delivery-body').scrollTop=y;if(delivery.querySelector('.categories'))delivery.querySelector('.categories').scrollLeft=x;});}
function basketMarkup(){if(!count())return '<div class="empty-basket"><h3>Пока ничего нет</h3><p>Выберите блюда в меню — они появятся здесь.</p></div>';return guruMenu.filter(p=>basket.has(p.id)).map(p=>`<article class="basket-item"><img src="${p.image}" alt=""><div><h4>${p.name}</h4><p>${rub(p.price)} за порцию</p>${controls(p)}</div><strong>${rub(p.price*basket.get(p.id))}</strong></article>`).join('');}
function openGuruDelivery(){location.hash='guru/delivery';}